apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # adds 301 redirect with trailing slash
    nginx.ingress.kubernetes.io/configuration-snippet: rewrite ^(/ocelot)$ $1/ permanent;
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /ocelot(/|$)(.*)
            backend:
              serviceName: {{ .Release.Name }}
              servicePort: http
